# Generated by Django 5.1.4 on 2025-01-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menus',
        ),
    ]
