# Generated by Django 5.1.4 on 2025-01-18 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_menu_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='allcaregories',
            old_name='menu',
            new_name='departments',
        ),
        migrations.AddField(
            model_name='category',
            name='departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.departments'),
            preserve_default=False,
        ),
    ]
