# Generated by Django 5.1.4 on 2025-01-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_menus_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcaregories',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.departments'),
        ),
        migrations.AlterField(
            model_name='category',
            name='allcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.allcaregories'),
        ),
    ]
